[package]
authors = ["Samray Leung <samrayleung@gmail.com>"]
name = "rspotify"
version = "0.2.4"
license = "MIT"
readme = "README.md"
description="Spotify API wrapper"
homepage="https://github.com/samrayleung/rspotify"
repository="https://github.com/samrayleung/rspotify"
keywords=["spotify","api"]
[dependencies]
base64 = "~0.6.0"
derive_builder = "0.5.1"
dotenv = "0.10.1"
env_logger = "0.5.3"
hyper = "0.11"
itertools = "0.7.6"
log = "0.4"
percent-encoding = "1.0.1"
rand = "0.4.2"
random = "0.12.2"
reqwest = "0.8.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
url = "1.6.0"
webbrowser = "0.2.2"
lazy_static = "1.0"
failure = "0.1"
lru = "0.1.8"

[dependencies.chrono]
features = ["serde", "rustc-serialize"]
version = "0.4"
